version: '3'

services:
    nest:
        build: ./packages/nest
        ports:
            - '10086:3000'

    wechaty:
        image: wechaty/wechaty
        command: index.ts
        volumes:
            - ./packages/wechaty-bot:/bot

networks:
    default:
        name: wechaty-doraemon

volumes:
    wechaty-doraemon_wechaty:
